#!/usr/bin/python
import sys
import os.path

try:
    import whiteshoe.client
except ImportError:
    sys.path.insert(0, os.path.join('.','src'))
    import whiteshoe.client

sys.exit(whiteshoe.client.client_main())
