#!/usr/bin/env python
import sys
import os.path

try:
    import whiteshoe.server
except ImportError:
    sys.path.insert(0, os.path.join('.','src'))
    import whiteshoe.server

sys.exit(whiteshoe.server.server_main())
